"""Fetch VIIRS nighttime light / airglow data.

The VIIRS Day/Night Band (DNB) on Suomi NPP and NOAA-20 satellites
detects extremely faint light at night, including:
    - City lights and anthropogenic sources
    - Atmospheric airglow (~90km altitude O2/OH emission)
    - Lightning, fires, and aurora

Physical mechanism:
    Acoustic-gravity waves generated by pre-seismic ground deformation
    propagate upward and modulate airglow emission patterns at ~90km.
    This has been observed before several major earthquakes. The effect
    is separate from ionospheric TEC changes (higher altitude).

    Additionally, nighttime light anomalies in coastal/offshore areas
    could indicate bioluminescence changes from submarine activity.

Data source: EOG (Earth Observation Group, Colorado School of Mines)
    - Monthly cloud-free composites (VIIRS VNP46A4)
    - No authentication for composites
    - Daily data requires Earthdata auth via LAADS DAAC

Target features:
    - nightlight_anomaly: radiance deviation from 6-month baseline (σ)

References:
    - Ouzounov et al. (2022) Remote Sensing 14:4960 (multi-parameter
      approach including nighttime thermal/light before 2020 Samos M7.0)
    - Molchanov et al. (2004) NHESS 4:703-712 (airglow observations)
"""

import asyncio
import logging
import os
import re
import sys
from datetime import datetime, timezone
from pathlib import Path

import aiohttp
import aiosqlite

sys.path.insert(0, str(Path(__file__).parent.parent / "src"))
from db import init_db
from config import DB_PATH

logging.basicConfig(level=logging.INFO, format="%(asctime)s [%(levelname)s] %(message)s")
logger = logging.getLogger(__name__)

# EOG VIIRS monthly composites (no auth, GeoTIFF/CSV)
# Average radiance composites
EOG_BASE = "https://eogdata.mines.edu/nighttime_light/monthly_notile/v10"

# Japan bbox
JAPAN_LAT_MIN = 24.0
JAPAN_LAT_MAX = 46.0
JAPAN_LON_MIN = 122.0
JAPAN_LON_MAX = 150.0

MAX_RETRIES = 3
TIMEOUT = aiohttp.ClientTimeout(total=600, connect=60)


async def init_nightlight_table():
    """Create nighttime light table."""
    async with aiosqlite.connect(DB_PATH) as db:
        await db.execute("""
            CREATE TABLE IF NOT EXISTS nightlight (
                id INTEGER PRIMARY KEY AUTOINCREMENT,
                observed_at TEXT NOT NULL,
                cell_lat REAL NOT NULL,
                cell_lon REAL NOT NULL,
                radiance_nw_cm2_sr REAL NOT NULL,
                received_at TEXT NOT NULL,
                UNIQUE(observed_at, cell_lat, cell_lon)
            )
        """)
        await db.execute("""
            CREATE INDEX IF NOT EXISTS idx_nl_time
            ON nightlight(observed_at)
        """)
        await db.commit()


async def fetch_eog_monthly_stats(session: aiohttp.ClientSession,
                                    year: int, month: int) -> list[dict]:
    """Fetch monthly VIIRS nighttime light statistics for Japan.

    EOG provides pre-computed statistics. We try multiple URL patterns
    as the format has changed over the years.
    """
    ym = f"{year}{month:02d}"

    # Try different URL patterns for EOG monthly data
    # The catalog structure varies by year
    urls = [
        # Newer format
        f"{EOG_BASE}/{year}/{ym}/vcmcfg/",
        # Older format
        f"{EOG_BASE}/{year}/{ym}/vcmslcfg/",
    ]

    for url in urls:
        try:
            async with session.get(url, timeout=TIMEOUT) as resp:
                if resp.status == 200:
                    text = await resp.text()
                    # Look for Japan tile files
                    # EOG tiles: 75N060W, 75N060E, etc.
                    # Japan is roughly in 75N060E tile
                    logger.info("EOG %s: catalog accessible", ym)
                    return []  # Catalog found but tile parsing needed
                elif resp.status == 404:
                    continue
        except (aiohttp.ClientError, asyncio.TimeoutError):
            continue

    return []


async def fetch_viirs_via_laads(session: aiohttp.ClientSession,
                                  year: int, month: int) -> list[dict]:
    """Fetch VIIRS DNB monthly from LAADS DAAC (Earthdata auth).

    Uses the VNP46A4 monthly gridded product.
    """
    earthdata_token = os.environ.get("EARTHDATA_TOKEN")
    if not earthdata_token:
        return []

    # LAADS DAAC search for VNP46A4 (monthly)
    search_url = (
        f"https://ladsweb.modaps.eosdis.nasa.gov/api/v2/content/details/"
        f"allData/5200/VNP46A4/{year}/"
    )

    headers = {"Authorization": f"Bearer {earthdata_token}"}

    try:
        async with session.get(search_url, timeout=TIMEOUT, headers=headers) as resp:
            if resp.status == 200:
                data = await resp.json()
                logger.info("LAADS VNP46A4 %d: %d granules found",
                            year, len(data) if isinstance(data, list) else 0)
                # Would need to download and parse HDF5 — complex
                # For now, log availability
                return []
            elif resp.status in (401, 403):
                logger.info("LAADS requires valid Earthdata token")
    except (aiohttp.ClientError, asyncio.TimeoutError) as e:
        logger.debug("LAADS VIIRS: %s", type(e).__name__)

    return []


async def main():
    await init_db()
    await init_nightlight_table()

    now = datetime.now(timezone.utc).isoformat()
    current_year = datetime.now(timezone.utc).year

    logger.info("=== VIIRS Nighttime Light Fetch ===")

    # Check existing
    async with aiosqlite.connect(DB_PATH) as db:
        existing = await db.execute_fetchall(
            "SELECT COUNT(*), MAX(observed_at) FROM nightlight"
        )
    n_existing = existing[0][0] if existing else 0
    logger.info("Nightlight existing: %d records", n_existing)

    async with aiohttp.ClientSession() as session:
        # Try EOG monthly composites first (no auth)
        for year in range(2012, current_year + 1):  # VIIRS starts April 2012
            for month in range(1, 13):
                if year == current_year and month > datetime.now().month:
                    break
                rows = await fetch_eog_monthly_stats(session, year, month)
                if rows:
                    async with aiosqlite.connect(DB_PATH) as db:
                        await db.executemany(
                            """INSERT OR IGNORE INTO nightlight
                               (observed_at, cell_lat, cell_lon, radiance_nw_cm2_sr, received_at)
                               VALUES (?, ?, ?, ?, ?)""",
                            [(r["date"], r["lat"], r["lon"], r["radiance"], now) for r in rows],
                        )
                        await db.commit()
                    logger.info("VIIRS %d-%02d: %d records", year, month, len(rows))
                await asyncio.sleep(0.5)

        # Try LAADS DAAC if EOG didn't work
        if n_existing == 0:
            await fetch_viirs_via_laads(session, current_year, 1)

    logger.info(
        "VIIRS nighttime fetch complete. "
        "Note: EOG monthly composites are large GeoTIFF files. "
        "Full implementation requires tile download + spatial subset. "
        "Nightlight features will be excluded via dynamic selection if no data."
    )


if __name__ == "__main__":
    asyncio.run(main())
